version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: cargo
    directory: "/ffi"
    schedule:
      interval: "monthly"
  - package-ecosystem: cargo
    directory: "/mitmproxy-windows/redirector"
    schedule:
      interval: "monthly"
  - package-ecosystem: cargo
    directory: "/wireguard-test-client"
    schedule:
      interval: "monthly"
